/*  =========================================================================

    sam_selftest - run all self tests

    This Source Code Form is subject to the terms of the MIT
    License. If a copy of the MIT License was not distributed with
    this file, You can obtain one at http://opensource.org/licenses/MIT

    =========================================================================
*/
/**

   @brief run all self tests
   @file sam_selftest.c

   This file is used to offer an entry point to run all self
   tests. While there must not always appear a direct result in the
   terminal, it is very convenient to run all functions at least
   once. This checks if any inner assert signals SIGABRT and external
   programs can be used to check for memory leaks/segfaults and do
   heap profiling.

*/


#include "../include/sam_prelude.h"
#include "../include/samd.h"


// all of this should get autogenerated in the future
typedef void *(*test_fn_t) ();


/// all possible functions
typedef enum {
    FN_SAM_LOG,           ///< for src/sam_log.c
    FN_SAM_GEN,           ///< for src/sam_gen.c
    /* FN_SAM_MSG,           ///< for src/sam_msg.c */
    /* FN_SAM_BE_RMQ,        ///< for src/sam_be_rmq.c */
    /* FN_SAM,               ///< for src/sam.c */
    /* FN_SAMD               ///< for src/samd.c */
} test_fn;


//  --------------------------------------------------------------------------
/// Print all necessary information for user invoking this
/// program. The function calls exit () with the provided return code.
static void
rtfm (int rc)
{
    printf ("sam selftest\n");
    printf ("usage: sam_selftest [-h] [--only SAM_MODULE]\n");
    printf ("options:\n");
    printf ("  -h: Print this message and exit\n");
    printf ("\n");
    printf ("You can selectively run tests by setting the CK_RUN_SUITE and\n");
    printf ("CK_RUN_CASE environment variables.");
    printf ("\n");
    exit (rc);
}


//  --------------------------------------------------------------------------
/// Returns a pointer to a function based on the provided test_fn enum
/// value.
static test_fn_t
get_test_fn (test_fn fn)
{
    switch (fn) {

    case FN_SAM_LOG:
        return sam_log_test;

    case FN_SAM_GEN:
        return sam_gen_test;

    /* case FN_SAM_MSG: */
    /*     return sam_msg_test; */

    /* case FN_SAM_BE_RMQ: */
    /*     return sam_be_rmq_test; */

    /* case FN_SAM: */
    /*     return sam_test; */

    /* case FN_SAMD: */
    /*     return samd_test; */

    default:
        assert (false);
    }
}


//  --------------------------------------------------------------------------
/// Run tests.
int main (int arg_c, char **arg_v)
{
    Suite *s = get_test_fn (0) ();
    SRunner *sr = srunner_create (s);

    test_fn fn_c = 1;
    for (; fn_c <= FN_SAM_GEN; fn_c ++) {
        s = get_test_fn (fn_c) ();
        srunner_add_suite (sr, s);
    }

    srunner_set_fork_status (sr, CK_NOFORK);
    srunner_run_all (sr, CK_NORMAL);

    int failed = srunner_ntests_failed (sr);
    srunner_free (sr);

    return (failed) ? 2 : 0;
}
